# Generated by Django 4.2.23 on 2025-08-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('design_type', models.CharField(choices=[('icon', 'Icon'), ('logo', 'Logo'), ('poster', 'Poster')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/images')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
