# Generated by Django 4.2.23 on 2025-08-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='field_upload',
            new_name='file_upload',
        ),
        migrations.AddField(
            model_name='order',
            name='final_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/final_files'),
        ),
    ]
